create table domaine (id_domaine bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id_domaine)) engine=InnoDB;
create table emprunt (id_emprunt bigint not null auto_increment, date_debut varchar(255), date_fin varchar(255), type integer, motif bigint, id_lecteur bigint, id_livre bigint not null, primary key (id_emprunt)) engine=InnoDB;
create table incident (id_incident bigint not null auto_increment, motif varchar(255), primary key (id_incident)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), dispo bit, editeur varchar(255), etat_livre integer, titre varchar(255), domaine bigint, primary key (id_livre)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, id_personne bigint not null auto_increment, adresse varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), telephone varchar(255), password varchar(255), username varchar(255), primary key (id_personne)) engine=InnoDB;
alter table emprunt add constraint UK_nauf36pnfpjw7depdk3yl50ik unique (id_livre);
alter table emprunt add constraint FK5owklyslb4g6njcu8omc53unp foreign key (motif) references incident (id_incident);
alter table emprunt add constraint FK4wj65w7ulgjwick3b8hwn5tem foreign key (id_lecteur) references personne (id_personne);
alter table emprunt add constraint FK2c4tf1n0sr8wpaxsw4f3ec2ur foreign key (id_livre) references livre (id_livre);
alter table livre add constraint FKno6aivssoq8j0vo4ddxgp9eyd foreign key (domaine) references domaine (id_domaine);
create table domaine (id_domaine bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id_domaine)) engine=InnoDB;
create table emprunt (id_emprunt bigint not null auto_increment, date_debut varchar(255), date_fin varchar(255), type integer, motif bigint, id_lecteur bigint, id_livre bigint not null, primary key (id_emprunt)) engine=InnoDB;
create table incident (id_incident bigint not null auto_increment, motif varchar(255), primary key (id_incident)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), dispo bit, editeur varchar(255), etat_livre integer, titre varchar(255), domaine bigint, primary key (id_livre)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, id_personne bigint not null auto_increment, adresse varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), telephone varchar(255), password varchar(255), username varchar(255), primary key (id_personne)) engine=InnoDB;
alter table emprunt add constraint UK_nauf36pnfpjw7depdk3yl50ik unique (id_livre);
alter table emprunt add constraint FK5owklyslb4g6njcu8omc53unp foreign key (motif) references incident (id_incident);
alter table emprunt add constraint FK4wj65w7ulgjwick3b8hwn5tem foreign key (id_lecteur) references personne (id_personne);
alter table emprunt add constraint FK2c4tf1n0sr8wpaxsw4f3ec2ur foreign key (id_livre) references livre (id_livre);
alter table livre add constraint FKno6aivssoq8j0vo4ddxgp9eyd foreign key (domaine) references domaine (id_domaine);
create table domaine (id_domaine bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id_domaine)) engine=InnoDB;
create table emprunt (id_emprunt bigint not null auto_increment, date_debut varchar(255), date_fin varchar(255), type integer, motif bigint, id_lecteur bigint, id_livre bigint not null, primary key (id_emprunt)) engine=InnoDB;
create table incident (id_incident bigint not null auto_increment, motif varchar(255), primary key (id_incident)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), dispo bit, editeur varchar(255), etat_livre integer, titre varchar(255), domaine bigint, primary key (id_livre)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, id_personne bigint not null auto_increment, adresse varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), telephone varchar(255), password varchar(255), username varchar(255), primary key (id_personne)) engine=InnoDB;
alter table emprunt add constraint UK_nauf36pnfpjw7depdk3yl50ik unique (id_livre);
alter table emprunt add constraint FK5owklyslb4g6njcu8omc53unp foreign key (motif) references incident (id_incident);
alter table emprunt add constraint FK4wj65w7ulgjwick3b8hwn5tem foreign key (id_lecteur) references personne (id_personne);
alter table emprunt add constraint FK2c4tf1n0sr8wpaxsw4f3ec2ur foreign key (id_livre) references livre (id_livre);
alter table livre add constraint FKno6aivssoq8j0vo4ddxgp9eyd foreign key (domaine) references domaine (id_domaine);
create table domaine (id_domaine bigint not null auto_increment, description varchar(255), nom varchar(255), primary key (id_domaine)) engine=InnoDB;
create table emprunt (id_emprunt bigint not null auto_increment, date_debut varchar(255), date_fin varchar(255), type integer, motif bigint, id_lecteur bigint, id_livre bigint not null, primary key (id_emprunt)) engine=InnoDB;
create table incident (id_incident bigint not null auto_increment, motif varchar(255), primary key (id_incident)) engine=InnoDB;
create table livre (id_livre bigint not null auto_increment, auteur varchar(255), dispo bit, editeur varchar(255), etat_livre integer, titre varchar(255), domaine bigint, primary key (id_livre)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, id_personne bigint not null auto_increment, adresse varchar(255), email varchar(255), nom varchar(255), prenom varchar(255), telephone varchar(255), password varchar(255), username varchar(255), primary key (id_personne)) engine=InnoDB;
alter table emprunt add constraint UK_nauf36pnfpjw7depdk3yl50ik unique (id_livre);
alter table emprunt add constraint FK5owklyslb4g6njcu8omc53unp foreign key (motif) references incident (id_incident);
alter table emprunt add constraint FK4wj65w7ulgjwick3b8hwn5tem foreign key (id_lecteur) references personne (id_personne);
alter table emprunt add constraint FK2c4tf1n0sr8wpaxsw4f3ec2ur foreign key (id_livre) references livre (id_livre);
alter table livre add constraint FKno6aivssoq8j0vo4ddxgp9eyd foreign key (domaine) references domaine (id_domaine);
