alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;

alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
alter table emprunt drop foreign key FK5owklyslb4g6njcu8omc53unp;
alter table emprunt drop foreign key FK4wj65w7ulgjwick3b8hwn5tem;
alter table emprunt drop foreign key FK2c4tf1n0sr8wpaxsw4f3ec2ur;
alter table livre drop foreign key FKno6aivssoq8j0vo4ddxgp9eyd;
drop table if exists domaine;
drop table if exists emprunt;
drop table if exists incident;
drop table if exists livre;
drop table if exists personne;
